# CAPTCHA Generator Configuration
# This file configures the generation of CAPTCHAs for different difficulty levels

# Global settings
output_dir: "data_generated"

# Part-specific configurations
parts:
  part2:
    # Basic enhanced alphanumeric CAPTCHAs (3-7 characters)
    num_samples: 10
    width: 640
    height: 160
    min_length: 3
    max_length: 7
    
    # Font configuration (leave empty to auto-detect system fonts)
    fonts: []  # Will use system fonts automatically
    # font_sizes: [60, 70, 80, 90]  # Larger fonts for 640x160 resolution
    font_sizes: [45, 55, 65, 75]  # Larger fonts for 640x160 resolution
    
    # Color configuration (optional - leave null for random colors)
    bg_color: null  # null for random, or specify as [R, G, B] e.g., [240, 240, 240]
    fg_color: null  # null for random, or specify as [R, G, B] e.g., [50, 50, 50]
    
    # Description: Clean alphanumeric CAPTCHAs with moderate distortions
    
  part3:
    # Medium degradation CAPTCHAs
    num_samples: 10
    width: 640
    height: 160
    min_length: 4
    max_length: 6
    
    fonts: []
    # font_sizes: [65, 75, 85, 95]  # Larger fonts for 640x160 resolution
    font_sizes: [45, 55, 65, 75]  # Larger fonts for 640x160 resolution
    
    bg_color: null
    fg_color: null
    
    # Description: Enhanced distortions, line distractors, complex backgrounds
    
  part4:
    # High degradation CAPTCHAs
    num_samples: 10
    width: 640
    height: 160
    min_length: 4
    max_length: 6
    
    fonts: []
    # font_sizes: [70, 80, 90, 100]  # Larger fonts for 640x160 resolution
    font_sizes: [45, 55, 65, 75]  # Larger fonts for 640x160 resolution
    
    bg_color: null
    fg_color: null
    
    # Description: Maximum difficulty with all distractors and effects

# Advanced font configuration (optional)
# If you want to specify custom fonts, uncomment and modify:
# custom_fonts:
#   - "/path/to/font1.ttf"
#   - "/path/to/font2.ttf"
#   - "/path/to/font3.ttf"

# Example with specific colors:
# parts:
#   part2:
#     bg_color: [245, 245, 245]  # Light gray background
#     fg_color: [30, 30, 30]     # Dark text